name: machinelearning-env
dependencies:
 - python=3.7
 #- pip=20.2.4
 - pip:
   - matplotlib==3.4
   - psutil >=5.8,<5.9
   - tqdm >=4.59,<4.60
   - pandas >=1.1,<1.2
   - numpy >=1.10,<1.20
   - scipy ~=1.5.0
   - scikit-learn ~=0.24.1
   - xgboost ~=1.4.0
   - lightgbm ~=3.2.0
   - dask ~=2021.6.0
   - distributed ~=2021.6.0
   - dask-ml ~=1.9.0
   - adlfs ~=0.7.0
   - ipykernel ~=6.0
   - azureml-core==1.36.0.post1
   - azureml-defaults==1.36.0
   - azureml-mlflow==1.36.0
   - azureml-telemetry==1.36.0
